/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/generator/scene.gltf -t -r public 
Author: Eh (https://sketchfab.com/Just_Eh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-generator-685fc34284574996b09ae0f826367e90
Title: Sci-fi Generator
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_14: THREE.Mesh
    Object_16: THREE.Mesh
    Object_17: THREE.Mesh
    Object_18: THREE.Mesh
    Object_20: THREE.Mesh
    Object_21: THREE.Mesh
    Object_22: THREE.Mesh
    Object_24: THREE.Mesh
    Object_26: THREE.Mesh
    Object_27: THREE.Mesh
    Object_29: THREE.Mesh
    Object_30: THREE.Mesh
    Object_32: THREE.Mesh
    Object_34: THREE.Mesh
    Object_35: THREE.Mesh
    Object_36: THREE.Mesh
    Object_38: THREE.Mesh
    Object_39: THREE.Mesh
    Object_40: THREE.Mesh
    Object_42: THREE.Mesh
    Object_43: THREE.Mesh
    Object_44: THREE.Mesh
    Object_46: THREE.Mesh
    Object_47: THREE.Mesh
    Object_48: THREE.Mesh
    Object_49: THREE.Mesh
    Object_51: THREE.Mesh
    Object_52: THREE.Mesh
    Object_53: THREE.Mesh
    Object_55: THREE.Mesh
    Object_56: THREE.Mesh
    Object_58: THREE.Mesh
    Object_59: THREE.Mesh
    Object_61: THREE.Mesh
    Object_63: THREE.Mesh
    Object_65: THREE.Mesh
    Object_67: THREE.Mesh
    Object_69: THREE.Mesh
    Object_70: THREE.Mesh
    Object_71: THREE.Mesh
    Object_73: THREE.Mesh
    Object_74: THREE.Mesh
    Object_76: THREE.Mesh
    Object_77: THREE.Mesh
    Object_79: THREE.Mesh
    Object_81: THREE.Mesh
    Object_82: THREE.Mesh
    Object_84: THREE.Mesh
    Object_85: THREE.Mesh
    Object_87: THREE.Mesh
    Object_89: THREE.Mesh
    Object_91: THREE.Mesh
    Object_92: THREE.Mesh
    Object_94: THREE.Mesh
    Object_96: THREE.Mesh
    Object_98: THREE.Mesh
    Object_99: THREE.Mesh
    Object_101: THREE.Mesh
    Object_103: THREE.Mesh
    Object_105: THREE.Mesh
    Object_107: THREE.Mesh
    Object_109: THREE.Mesh
    Object_110: THREE.Mesh
    Object_112: THREE.Mesh
    Object_114: THREE.Mesh
    Object_115: THREE.Mesh
    Object_117: THREE.Mesh
    Object_119: THREE.Mesh
    Object_121: THREE.Mesh
    Object_123: THREE.Mesh
    Object_125: THREE.Mesh
    Object_127: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    RED_STILL: THREE.MeshStandardMaterial
    material_0: THREE.MeshStandardMaterial
    ELECTRO: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/generator/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.244, 4.52, 0]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material.005']} />
      </group>
      <group position={[-1.285, 7.038, 0]}>
        <mesh geometry={nodes.Object_12.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['Material.007']} />
      </group>
      <group position={[-1.036, 2.645, -0.014]}>
        <mesh geometry={nodes.Object_16.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_17.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_18.geometry} material={materials['Material.005']} />
      </group>
      <group position={[1.13, 6.574, 0]}>
        <mesh geometry={nodes.Object_20.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Object_21.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.Material} />
      </group>
      <group position={[-0.353, 4.903, 1.106]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_26.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Object_27.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-0.811, 4.946, 1.395]}>
        <mesh geometry={nodes.Object_29.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_30.geometry} material={materials['Material.003']} />
      </group>
      <group position={[0.77, 5.661, 0]} rotation={[0, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_34.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_35.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_36.geometry} material={materials['Material.005']} />
      </group>
      <group position={[1.015, 2.525, 0]} rotation={[0, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_38.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Object_39.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.Material} />
      </group>
      <group position={[0.887, 3.457, 0.003]} rotation={[0, 0, -1.037]}>
        <mesh geometry={nodes.Object_42.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_43.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Object_44.geometry} material={materials['Material.005']} />
      </group>
      <group position={[0.6, 8.499, 0.513]} rotation={[Math.PI / 2, 0.417, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_46.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Object_47.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Object_48.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_49.geometry} material={materials['Material.007']} />
      </group>
      <group position={[-1.403, 4.946, 1.801]}>
        <mesh geometry={nodes.Object_51.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_52.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_53.geometry} material={materials['Material.005']} />
      </group>
      <group position={[0.913, 4.876, -0.25]}>
        <mesh geometry={nodes.Object_55.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.RED_STILL} />
      </group>
      <group position={[0.976, 1.769, 0.517]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_58.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_59.geometry} material={materials.RED_STILL} />
      </group>
      <group position={[0.77, 4.229, 0.53]} rotation={[0, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_69.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Object_70.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Object_71.geometry} material={materials.Material} />
      </group>
      <group position={[0.695, 3.841, 0.306]} rotation={[0, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_73.geometry} material={materials.RED_STILL} />
        <mesh geometry={nodes.Object_74.geometry} material={materials['Material.003']} />
      </group>
      <group position={[0.93, 5.817, -0.561]} rotation={[0, 0, -Math.PI]}>
        <mesh geometry={nodes.Object_76.geometry} material={materials.RED_STILL} />
        <mesh geometry={nodes.Object_77.geometry} material={materials['Material.003']} />
      </group>
      <group position={[0.774, 4.023, 0]}>
        <mesh geometry={nodes.Object_81.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_82.geometry} material={materials.RED_STILL} />
      </group>
      <group position={[0.976, 1.193, 0]}>
        <mesh geometry={nodes.Object_84.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_85.geometry} material={materials.RED_STILL} />
      </group>
      <group position={[0.757, 4.793, 0.586]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_91.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_92.geometry} material={materials.RED_STILL} />
      </group>
      <group position={[0.811, 5.655, 0.094]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_98.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_99.geometry} material={materials.RED_STILL} />
      </group>
      <group position={[0.374, 1.335, 1.056]} scale={[0.01, 0.031, 0.01]}>
        <mesh geometry={nodes.Object_109.geometry} material={materials.RED_STILL} />
        <mesh geometry={nodes.Object_110.geometry} material={materials['Material.005']} />
      </group>
      <group position={[-0.873, 9.779, -0.548]} rotation={[0, Math.PI / 2, 0]} scale={0.367}>
        <mesh geometry={nodes.Object_114.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Object_115.geometry} material={materials.RED_STILL} />
      </group>
      <mesh geometry={nodes.Object_10.geometry} material={materials['Material.007']} position={[-2.193, 1.279, 0]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.Material} position={[1.078, 0.583, 0]} />
      <mesh geometry={nodes.Object_32.geometry} material={materials['Material.006']} position={[0.955, 7.007, 0.381]} />
      <mesh geometry={nodes.Object_61.geometry} material={materials['Material.002']} position={[0.989, 1.193, 0.518]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_63.geometry} material={materials['Material.007']} position={[0.792, 3.69, 0.518]} rotation={[-0.991, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_65.geometry} material={materials['Material.007']} position={[1.037, 3.191, 0.518]} rotation={[-0.217, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_67.geometry} material={materials['Material.006']} position={[0.734, 4.155, 0]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_79.geometry} material={materials['Material.006']} position={[1.005, 1.886, 0.654]} />
      <mesh geometry={nodes.Object_87.geometry} material={materials['Material.005']} position={[1.156, 0.379, 0.993]} />
      <mesh geometry={nodes.Object_89.geometry} material={materials.Material} position={[0.681, 4.782, 0.733]} />
      <mesh geometry={nodes.Object_94.geometry} material={materials['Material.006']} position={[0.734, 5.466, 0]} rotation={[-Math.PI, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_96.geometry} material={materials['Material.007']} position={[0.768, 5.494, 0.331]} rotation={[-0.217, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_101.geometry} material={materials.Material} position={[1.073, 6.523, 0]} rotation={[Math.PI, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_103.geometry} material={materials['Material.005']} position={[1.038, 6.523, 0]} rotation={[Math.PI, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_105.geometry} material={materials.Material} position={[0.434, 8.434, 0]} />
      <mesh geometry={nodes.Object_107.geometry} material={materials['Material.005']} position={[0.993, 7.075, 0.993]} scale={[0.147, 0.147, 0.025]} />
      <mesh geometry={nodes.Object_112.geometry} material={materials.material_0} position={[0.955, 1.488, 0]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_117.geometry} material={materials['Material.005']} position={[-0.883, 9.624, 0.669]} rotation={[0, 0, -Math.PI / 2]} scale={1.938} />
      <mesh geometry={nodes.Object_119.geometry} material={materials['Material.007']} position={[0.792, 3.69, -0.519]} rotation={[-0.695, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_121.geometry} material={materials['Material.007']} position={[1.037, 3.191, -0.519]} rotation={[-0.517, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_123.geometry} material={materials['Material.007']} position={[-1.473, 5.361, 1.806]} rotation={[-0.582, 0, 0]} />
      <mesh geometry={nodes.Object_125.geometry} material={materials['Material.007']} position={[-1.473, 4.537, 1.806]} rotation={[-0.043, 0, 0]} />
      <mesh geometry={nodes.Object_127.geometry} material={materials.ELECTRO} position={[0.994, 2.76, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.373} />
    </group>
  )
}

useGLTF.preload('/generator/scene.gltf')
