/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/surface/scene.gltf -t -r public 
Author: Šimon Ustal (https://sketchfab.com/simonustal)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/desert-landscape-220c14d161e44e83be64f30f2034cf4b
Title: Desert Landscape
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Plane_Material001_0: THREE.Mesh;
    Plane_Material001_0_1: THREE.Mesh;
    Plane_Material001_0_2: THREE.Mesh;
    Plane_Material001_0_3: THREE.Mesh;
    Plane_Material001_0_4: THREE.Mesh;
    Plane_Material001_0_5: THREE.Mesh;
  };
  materials: {
    ["Material.001"]: THREE.MeshStandardMaterial;
  };
};

export function Surface(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/surface/scene.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={191.328}>
          <mesh
            geometry={nodes.Plane_Material001_0.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            geometry={nodes.Plane_Material001_0_1.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            geometry={nodes.Plane_Material001_0_2.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            geometry={nodes.Plane_Material001_0_3.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            geometry={nodes.Plane_Material001_0_4.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            geometry={nodes.Plane_Material001_0_5.geometry}
            material={materials["Material.001"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/surface/scene.gltf");
