/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/surface/scene.gltf -t -r public 
Author: Nik (https://sketchfab.com/nikska)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mars-perseverance-landing-site-raw-scan-d017d148d0554061b0c8064eb648af56
Title: Mars Perseverance Landing Site - Raw Scan
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Model_material0_0: THREE.Mesh;
    Model_material0_0_1: THREE.Mesh;
  };
  materials: {
    material0: THREE.MeshStandardMaterial;
  };
};

export default function Surface(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/mars-surface/surface/scene.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[-0.053, 0.27, -0.126]} rotation={[-1.192, 0.174, -0.018]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh geometry={nodes.Model_material0_0.geometry} material={materials.material0} />
          <mesh geometry={nodes.Model_material0_0_1.geometry} material={materials.material0} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/mars-surface/surface/scene.gltf");
