/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/generator-small/scene.gltf -t -r public 
Author: PatrickStevens (https://sketchfab.com/PatrickStevens)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mars-base-crate-yellow-4107d7e6dfc848058c6175ce3267f49b
Title: Mars Base Crate Yellow
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
  };
  materials: {
    PRIMARY_MATERIAL: THREE.MeshStandardMaterial;
  };
};

export default function GeneratorSmall(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/mars-surface/generator-small/scene.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.PRIMARY_MATERIAL}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/mars-surface/generator-small/scene.gltf");
