/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/rocket/scene.gltf -t -r public 
Author: zguerrero (https://sketchfab.com/zguerrero)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/space-rocket-ec4ed8894c71468baf77f4f4d2f4f5ab
Title: Space Rocket
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    rocket_01_rocket_0: THREE.Mesh;
  };
  materials: {
    rocket: THREE.MeshStandardMaterial;
  };
};

export default function Rocket(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/mars-surface/rocket/scene.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={nodes.rocket_01_rocket_0.geometry}
          material={materials.rocket}
          position={[0, -966.887, 0]}
          rotation={[-Math.PI / 2, 0, 0.175]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/mars-surface/rocket/scene.gltf");
